Add support for native-image
This doesn't work right now, because it fails with

java.lang.IllegalArgumentException: URI with undefined scheme

inside the Spring interface clients.